#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd

while IFS=':' read -r username password uid gid comment home_dir shell
do 
	echo "$username:$uid:$home_dir"

done < /etc/passwd
