#!/usr/bin/env bash
#Tell the story of passwd

while IFS=':' read -r  username password uid gid comment home_dir shell
do
	echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $comment"

done < /etc/passwd
