#!/usr/bin/env bash
#Write a Bash script that displays Write a Bash script that displays In a list format Where only the part of the name after the first dash is displayed (refer to the example)

find . -maxdepth 1 -type f -printf '%f\n'  | cut -d "-" -f2- 

