#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file
if [ -e "school" ]; then
	if [ $? -eq 0 ]; then
		echo school file exists
	fi
		if [ ! -s "school" ]; then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi
			if [ -f "school" ]; then
				echo "school is a regular file"
			else
				:
			fi
	else
		echo school file does not exist
fi
